version: 2.1

jobs:
  build-portal:
    docker:
      - image: docker:dind
      
    steps:
      - checkout

      - run: |
          if [[ $(git branch --show-current) == "master" ]]; then
              TAG="latest"
          else
              TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
          fi
          docker build -t topiaas/portal:$TAG ./portal
          docker build -t topiaas/portalworker:$TAG -f portal/Dockerfile.worker .
          echo $DockerPass | docker login -u $DockerUserName --password-stdin
          docker push topiaas/portal:$TAG
          docker push topiaas/portalworker:$TAG

workflows:
  default:
    jobs:
      - build-portal
