version: 2.1

jobs:
  build-portal:
    docker:
      - image: circleci/golang:1.15
      
    steps:
      - checkout
      
      - setup_remote_docker:
          version: 19.03.13
          
      - run: |
          echo "$DockerPass"
         

workflows:
  default:
    jobs:
      - build-portal:
          context: DockerPass
