---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orangeml-0
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: "topiaas.ml"
      http:
        paths:
        - path: /orangeml-0/(.*)
          pathType: Prefix
          backend:
            service:
              name: orangeml-service-0
              port:
                number: 80
  tls:
    - hosts:
      -  "topiaas.ml"
      secretName: topiaas-ml-tls # TODO: change from being hardcoded
