version: "3.7"
services:
  topiaas-app:
    build:
      context: ".."
      dockerfile: .devcontainer/Dockerfile
    container_name: topiaas_devenv_1
    environment:
      SECRET_KEY: sercet_key
    volumes:
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - topiaas-net

  orangeml:
    build:
      context: "../engine/orangeml"
      dockerfile: Dockerfile.orange
    environment:
      PASSWORD: password2
    container_name: orangeml
    volumes:
      - ..:/workspace:cached
    networks:
      - topiaas-net

  inkscape:
    build:
      context: "../engine/inkscape"
      dockerfile: Dockerfile.inkscape
    environment:
      PASSWORD: password2
    container_name: inkscape
    volumes:
      - ..:/workspace:cached
    networks:
      - topiaas-net

  postgres:
    image: postgres:9.6.21
    environment:
      POSTGRES_USER: devel
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db
    networks:
      - topiaas-net
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6.2.1-alpine
    networks:
      - topiaas-net

volumes:
  db-data:
    driver: local

networks:
  topiaas-net:
    driver: bridge
