version: "3.7"
services:
  topiaas-app:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: topiaas_devenv_1
    environment: 
      SECRET_KEY: sercet_key
    volumes: 
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - topiaas-net

  topiaas-mongodb:
    image: bitnami/mongodb:latest
    container_name: topiaas_mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/mongodb

    restart: unless-stopped
    networks:
      - topiaas-net


volumes:
  mongodb_data:
    driver: local

    
networks:
  topiaas-net:
    driver: bridge