# Install using
# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm install redis bitnami/redis --values kubernetes/redis/values.yaml

replica:
  replicaCount: 1
  persistence:
    size: 2Gi
    storageClass: manual

sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled