---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topiaas-deployment
  labels:
    app: topiaas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: topiaas
  template:
    metadata:
      labels:
        app: topiaas
    spec:
      containers:
      - name: topiaas
        image: topiaas/portal:0e2fa894c8e7ceabd2e53a0ccd34fbff4f5c9437
        ports:
        - containerPort: 5000
        env:
          - name: APP_NAME
            value: Topiaas
          - name: FLASK_CONFIG
            value: production
          - name: REDISTOGO_URL
            value: "http://redis:6379"
          - name: DATABASE_USER
            value: devel
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_SERVICE_NAME
            value: my-release-postgresql-ha-postgresql 
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-release-postgresql-ha-postgresql
                key: postgresql-password
          - name: SECRET_KEY
            value: sercet_key #TODO: change
