name: Build and push orangeml image

on:
  push:
    paths: 
      - 'engine/orangeml/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: engine/orangeml/Dockerfile.orange
          context: engine/orangeml/
          push: true
          tags: topiaas/orangeml:${{ steps.vars.outputs.sha_short }}
