name: Build and push orangeml image

on:
  push:
    paths: 
      - 'engine/orangeml/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment:
      name: ApproveKubePatching
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: engine/orangeml/Dockerfile.orange
          context: engine/orangeml/
          push: true
          tags: topiaas/orangeml:${{ github.sha }}
